name = "kyle-proxy"
description = "Basic test hello world Go app"
internal = true
image = "precise64"
app_type = "go1.2"
run_command = "./ProxyEcho"
cpu_shares = 1
memory_limit = 128

dependencies = [
   "kyle-echo"
]
